#============================#
#===== Database sttings =====#
#============================#

#mysql database setting
#jdbc.type=mysql
url=jdbc:mysql://zxadwz.cn:3306/eat_what?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
driverClassName=com.mysql.cj.jdbc.Driver
username=root
password=Ok12345.
database=eat_what

#mssql database settings
#jdbc.type=mssql
#url=jdbc:sqlserver://localhost;databaseName=one_manage
#driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#username=sa
#password=123456
#database=one_manage


#other config
filters=stat
maxActive=20
initialSize=1
maxWait=60000
minIdle=10
maxIdle=15
timeBetweenEvictionRunsMillis=60000
minEvictableIdleTimeMillis=300000
validationQuery=SELECT 'x'
testWhileIdle=true
testOnBorrow=false
testOnReturn=false
maxOpenPreparedStatements=20
removeAbandoned=true
removeAbandonedTimeout=1800
logAbandoned=true